server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

#
#scrape_configs:
#  - job_name: service_01_logs
#    static_configs:
#    - targets:
#        - localhost
#      labels:
#        job: service_01
#        __path__: /logs/service_01/service_01*.log

#  - job_name: service_02_logs
#    static_configs:
#    - targets:
#        - localhost
#      labels:
#        job: service_02
#        __path__: /logs/service_02/service_02*.log

scrape_configs:
  - job_name: docker
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
    pipeline_stages:
      - docker: {}   # <- OBLIGATORIO el colon
    relabel_configs:
      - source_labels: ['__meta_docker_container_label_com_docker_compose_service']
        target_label: compose_service
      - source_labels: ['__meta_docker_container_label_com_docker_compose_project']
        target_label: compose_project
      - source_labels: ['__meta_docker_container_name']
        target_label: container
      - source_labels: ['__meta_docker_container_image']
        target_label: image