services:
  service_01:
    build: .
    ports:
      - "5000:80"
    volumes:
      - ./app:/code/app
    depends_on:
      - service_01_mongodb
  service_01_mongodb:
    image: mongo:5.0
    volumes:
      - service_01_mongodb_container:/data/db
    logging:
        driver: none

volumes:
  service_01_mongodb_container:

networks:
  default:
    name: Tarea1_INF326
    external: true